# -*- coding: utf-8 -*-
"""PI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFaNocaFIqIIlELeq9rkdbAhVfXXqSbe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

data = pd.read_csv('DadosTratados.csv')
data

data.describe()

y = data['INSCRITOS']
x1 = data ['TOTAL DE HABITANTES']

plt.scatter(x1,y)
plt.xlabel('TOTAL DE HABITANTES', fontsize=20)
plt.ylabel('INSCRITOS', fontsize=20)
plt.show()

x = sm.add_constant(x1)
results = sm.OLS(y,x).fit()
results.summary()

plt.scatter(x1,y)
yhat = 4.7673*x1 + 2.471
fig = plt.plot(x1,yhat, lw=4, c='orange', label = 'regressão linear') 
plt.xlabel('TOTAL DE HABITANTES',fontsize = 20)
plt.ylabel('INSCRITOS', fontsize = 20)
plt.show()

data = pd.read_csv('DadosTratados.csv')
plt.hist(x['INSCRITOS'], bins = 20)
plt.show()

data = pd.read_csv("DadosEnxutos.csv")
plt.pie(data["INSCRITOS"],labels = data['BAIRRO'])
plt.show()

data = pd.read_csv("DadosTratados.csv")
sns.displot(data['INSCRITOS'], rug = True);
sns.displot(data['TOTAL DE HABITANTES']);

